"""
Builds the HTML email from analysis results.
All formatting / template logic lives here — no business logic.
"""

import re
from datetime import datetime

from Config import CLAUDE_MODEL, TZ, REPORT_LANGUAGE


def build_email_html(
    analyses: list[tuple[dict, str]],
    usage_summary: dict | None = None,
) -> str:
    """Convert analysis results + usage stats into an HTML email string."""
    now = datetime.now(TZ)

    if REPORT_LANGUAGE == "ko":
        date_str = now.strftime("%Y년 %m월 %d일 %H:%M ET")
        header_title = "📈 일일 주식 분석 리포트"
        header_sub = f"{date_str} | 종목 {len(analyses)}개 분석"
        disclaimer = (
            "⚠️ 본 리포트는 AI 기반 자동 분석이며, 투자 권유가 아닙니다.<br>"
            "투자의 책임은 본인에게 있으며, 반드시 본인의 판단 하에 투자하세요."
        )
    else:
        date_str = now.strftime("%B %d, %Y %H:%M ET")
        header_title = "📈 Daily Stock Analysis Report"
        header_sub = f"{date_str} | {len(analyses)} stocks analyzed"
        disclaimer = (
            "⚠️ This report is AI-based automated analysis and is not investment advice.<br>"
            "Investment decisions are your own responsibility."
        )

    cards_html = "".join(_build_stock_card(sd, a) for sd, a in analyses)
    usage_html = _build_usage_section(usage_summary) if usage_summary else ""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,
             BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
    <div style="max-width:720px;margin:0 auto;padding:20px;">
        <div style="background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%);
                    border-radius:12px;padding:28px;margin-bottom:24px;text-align:center;">
            <h1 style="margin:0;color:#ffffff;font-size:24px;">{header_title}</h1>
            <p style="margin:8px 0 0;color:#bfdbfe;font-size:14px;">{header_sub}</p>
        </div>
        {cards_html}
        {usage_html}
        <div style="text-align:center;padding:20px;color:#9ca3af;font-size:11px;
                    border-top:1px solid #e5e7eb;margin-top:16px;">
            {disclaimer}<br><br>
            <strong>Model:</strong> {CLAUDE_MODEL}<br>
            Generated by Claude API + yfinance
        </div>
    </div>
</body>
</html>"""


def _build_stock_card(stock_data: dict, analysis: str) -> str:
    ticker = stock_data["ticker"]
    price = stock_data["current_price"]
    change = stock_data["daily_change_pct"]
    change_color = "#22c55e" if change >= 0 else "#ef4444"
    change_arrow = "▲" if change >= 0 else "▼"
    analysis_html = _markdown_to_html(analysis)

    return f"""
    <div style="background:#ffffff;border-radius:12px;padding:24px;margin-bottom:24px;
                box-shadow:0 1px 3px rgba(0,0,0,0.1);border:1px solid #e5e7eb;">
        <div style="display:flex;justify-content:space-between;align-items:center;
                    margin-bottom:16px;padding-bottom:12px;border-bottom:2px solid #f3f4f6;">
            <div>
                <h2 style="margin:0;font-size:22px;color:#111827;">
                    {stock_data['company_name']}
                    <span style="color:#6b7280;font-weight:normal;">({ticker})</span>
                </h2>
                <span style="font-size:13px;color:#9ca3af;">{stock_data['sector']}</span>
            </div>
            <div style="text-align:right;">
                <div style="font-size:28px;font-weight:bold;color:#111827;">${price}</div>
                <div style="font-size:15px;color:{change_color};font-weight:600;">
                    {change_arrow} {abs(change)}%
                </div>
            </div>
        </div>
        <div style="font-size:14px;line-height:1.7;color:#374151;">
            {analysis_html}
        </div>
    </div>"""


def _build_usage_section(summary: dict) -> str:
    today_cost = summary.get("today_cost_usd", 0)
    monthly_cost = summary.get("monthly_cost_usd", 0)
    total_in = summary.get("total_input_tokens", 0)
    total_out = summary.get("total_output_tokens", 0)
    total_ws = summary.get("total_web_searches", 0)
    model = summary.get("model", CLAUDE_MODEL)

    if REPORT_LANGUAGE == "ko":
        per_ticker_rows = ""
        for t in summary.get("per_ticker", []):
            per_ticker_rows += (
                f"<tr><td style='padding:4px 8px;'>{t['ticker']}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['input_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['output_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['web_searches']}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>${t['cost_usd']:.4f}</td></tr>"
            )

        return f"""
        <div style="background:#f0f9ff;border-radius:12px;padding:20px;margin-bottom:24px;
                    border:1px solid #bae6fd;">
            <h3 style="margin:0 0 12px;color:#0369a1;font-size:16px;">💰 API 사용량</h3>
            <table style="width:100%;font-size:13px;border-collapse:collapse;color:#374151;">
                <tr style="background:#e0f2fe;">
                    <th style="padding:6px 8px;text-align:left;">종목</th>
                    <th style="padding:6px 8px;text-align:right;">Input</th>
                    <th style="padding:6px 8px;text-align:right;">Output</th>
                    <th style="padding:6px 8px;text-align:right;">검색</th>
                    <th style="padding:6px 8px;text-align:right;">비용</th>
                </tr>
                {per_ticker_rows}
                <tr style="border-top:2px solid #0369a1;font-weight:bold;">
                    <td style="padding:6px 8px;">합계</td>
                    <td style="padding:6px 8px;text-align:right;">{total_in:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_out:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_ws}</td>
                    <td style="padding:6px 8px;text-align:right;">${today_cost:.4f}</td>
                </tr>
            </table>
            <p style="margin:12px 0 0;font-size:13px;color:#0369a1;">
                📊 오늘 비용: <strong>${today_cost:.2f}</strong> |
                이번 달 누적: <strong>${monthly_cost:.2f}</strong> |
                모델: {model}
            </p>
        </div>"""
    else:
        per_ticker_rows = ""
        for t in summary.get("per_ticker", []):
            per_ticker_rows += (
                f"<tr><td style='padding:4px 8px;'>{t['ticker']}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['input_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['output_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['web_searches']}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>${t['cost_usd']:.4f}</td></tr>"
            )

        return f"""
        <div style="background:#f0f9ff;border-radius:12px;padding:20px;margin-bottom:24px;
                    border:1px solid #bae6fd;">
            <h3 style="margin:0 0 12px;color:#0369a1;font-size:16px;">💰 API Usage</h3>
            <table style="width:100%;font-size:13px;border-collapse:collapse;color:#374151;">
                <tr style="background:#e0f2fe;">
                    <th style="padding:6px 8px;text-align:left;">Ticker</th>
                    <th style="padding:6px 8px;text-align:right;">Input</th>
                    <th style="padding:6px 8px;text-align:right;">Output</th>
                    <th style="padding:6px 8px;text-align:right;">Searches</th>
                    <th style="padding:6px 8px;text-align:right;">Cost</th>
                </tr>
                {per_ticker_rows}
                <tr style="border-top:2px solid #0369a1;font-weight:bold;">
                    <td style="padding:6px 8px;">Total</td>
                    <td style="padding:6px 8px;text-align:right;">{total_in:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_out:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_ws}</td>
                    <td style="padding:6px 8px;text-align:right;">${today_cost:.4f}</td>
                </tr>
            </table>
            <p style="margin:12px 0 0;font-size:13px;color:#0369a1;">
                📊 Today: <strong>${today_cost:.2f}</strong> |
                This Month: <strong>${monthly_cost:.2f}</strong> |
                Model: {model}
            </p>
        </div>"""


def _markdown_to_html(text: str) -> str:
    html = text
    html = re.sub(
        r"^## (.+)$",
        r"<h3 style='color:#1e40af;margin-top:20px;margin-bottom:8px;"
        r"border-bottom:2px solid #e5e7eb;padding-bottom:6px;'>\1</h3>",
        html, flags=re.MULTILINE,
    )
    html = re.sub(
        r"^### (.+)$",
        r"<h4 style='color:#1e40af;margin-top:16px;margin-bottom:6px;'>\1</h4>",
        html, flags=re.MULTILINE,
    )
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = _convert_md_tables(html)
    html = html.replace("\n", "<br>")
    return html


def _convert_md_tables(text: str) -> str:
    lines = text.split("\n")
    result = []
    table_lines = []
    in_table = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            if re.match(r"^\|[\s\-:|]+\|$", stripped):
                continue
            table_lines.append(stripped)
            in_table = True
        else:
            if in_table and table_lines:
                result.append(_table_lines_to_html(table_lines))
                table_lines = []
                in_table = False
            result.append(line)

    if table_lines:
        result.append(_table_lines_to_html(table_lines))

    return "\n".join(result)


def _table_lines_to_html(lines: list[str]) -> str:
    html = (
        "<table style='width:100%;border-collapse:collapse;margin:12px 0;"
        "font-size:13px;'>"
    )
    for i, line in enumerate(lines):
        cells = [c.strip() for c in line.strip("|").split("|")]
        tag = "th" if i == 0 else "td"
        bg = "background:#f3f4f6;" if i == 0 else ""
        border = "border:1px solid #e5e7eb;padding:6px 10px;"
        row = "<tr>"
        for cell in cells:
            row += f"<{tag} style='{border}{bg}'>{cell}</{tag}>"
        row += "</tr>"
        html += row
    html += "</table>"
    return html