"""
Builds the HTML email from analysis results.
All formatting / template logic lives here — no business logic.
"""

import re
from datetime import datetime
from html import escape

from config import CLAUDE_MODEL, TZ, REPORT_LANGUAGE


def build_email_html(
    analyses: list[tuple[dict, str]],
    usage_summary: dict | None = None,
    summaries: list[dict] | None = None,
) -> str:
    """Convert analysis results + usage stats into an HTML email string."""
    now = datetime.now(TZ)

    if REPORT_LANGUAGE == "ko":
        date_str = now.strftime("%Y년 %m월 %d일 %H:%M ET")
        header_title = "📈 일일 주식 분석 리포트"
        header_sub = f"{date_str} | 종목 {len(analyses)}개 분석"

    else:
        date_str = now.strftime("%B %d, %Y %H:%M ET")
        header_title = "📈 Daily Stock Analysis Report"
        header_sub = f"{date_str} | {len(analyses)} stocks analyzed"

    summary_by_ticker = {s.get("ticker"): s for s in summaries or []}
    cards_html = "".join(
        _build_stock_card(sd, a, summary_by_ticker.get(sd["ticker"]))
        for sd, a in analyses
    )
    usage_html = _build_usage_section(usage_summary) if usage_summary else ""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,
             BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
    <div style="max-width:720px;margin:0 auto;padding:20px;">
        <div style="background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%);
                    border-radius:12px;padding:28px;margin-bottom:24px;text-align:center;">
            <h1 style="margin:0;color:#ffffff;font-size:24px;">{header_title}</h1>
            <p style="margin:8px 0 0;color:#bfdbfe;font-size:14px;">{header_sub}</p>
        </div>
        {cards_html}
        {usage_html}
        <div style="text-align:center;padding:20px;color:#9ca3af;font-size:11px;
                    border-top:1px solid #e5e7eb;margin-top:16px;">
            <br>
            <strong>Model:</strong> {CLAUDE_MODEL}<br>
            Generated by Claude API + yfinance
        </div>
    </div>
</body>
</html>"""


def _build_stock_card(stock_data: dict, analysis: str, summary: dict | None = None) -> str:
    ticker = stock_data["ticker"]
    price = stock_data["current_price"]
    change = stock_data["daily_change_pct"]
    change_color = "#22c55e" if change >= 0 else "#ef4444"
    change_arrow = "▲" if change >= 0 else "▼"
    analysis_html = _markdown_to_html(analysis)
    polymarket_html = _build_polymarket_section(summary) if summary else ""

    return f"""
    <div style="background:#ffffff;border-radius:12px;padding:24px;margin-bottom:24px;
                box-shadow:0 1px 3px rgba(0,0,0,0.1);border:1px solid #e5e7eb;">
        <div style="display:flex;justify-content:space-between;align-items:center;
                    margin-bottom:16px;padding-bottom:12px;border-bottom:2px solid #f3f4f6;">
            <div>
                <h2 style="margin:0;font-size:22px;color:#111827;">
                    {stock_data['company_name']}
                    <span style="color:#6b7280;font-weight:normal;">({ticker})</span>
                </h2>
                <span style="font-size:13px;color:#9ca3af;">{stock_data['sector']}</span>
            </div>
            <div style="text-align:right;">
                <div style="font-size:28px;font-weight:bold;color:#111827;">${price}</div>
                <div style="font-size:15px;color:{change_color};font-weight:600;">
                    {change_arrow} {abs(change)}%
                </div>
            </div>
        </div>
        <div style="font-size:14px;line-height:1.7;color:#374151;">
            {analysis_html}
        </div>
        {polymarket_html}
    </div>"""


def _build_polymarket_section(summary: dict) -> str:
    pm = summary.get("polymarket")
    review = summary.get("polymarket_claude_review")
    comparison = summary.get("polymarket_comparison", {})

    if not pm and not review:
        return ""

    if REPORT_LANGUAGE == "ko":
        title = "Polymarket 사후 검토"
        direction_label = "Polymarket 방향"
        probability_label = "YES 확률"
        adjustment_label = "Claude 2차 판단"
        reason_label = "이유"
        no_market = "관련 Polymarket 시장 없음"
    else:
        title = "Polymarket Post-Review"
        direction_label = "Polymarket Direction"
        probability_label = "YES Probability"
        adjustment_label = "Claude Second-Pass View"
        reason_label = "Reason"
        no_market = "No related Polymarket market"

    if not pm or not pm.get("available"):
        body = escape((pm or {}).get("reason", no_market))
    else:
        question = escape(str(pm.get("question", "Unknown")))
        pm_direction = escape(str(pm.get("polymarket_direction", "unknown")))
        yes_prob = pm.get("probability_yes_pct", "N/A")
        match_msg = escape(str(comparison.get("message", "")))

        review_html = ""
        if review:
            adjustment = escape(str(review.get("confidence_adjustment", "unknown")))
            magnitude = escape(str(review.get("adjustment_magnitude", "unknown")))
            confidence = escape(str(review.get("final_confidence_after_polymarket", "unknown")))
            reason = escape(str(review.get("reason", "N/A")))
            review_html = (
                f"<p style='margin:8px 0 0;'><strong>{adjustment_label}:</strong> "
                f"{adjustment} ({magnitude}), confidence: {confidence}</p>"
                f"<p style='margin:6px 0 0;'><strong>{reason_label}:</strong> {reason}</p>"
            )

        body = (
            f"<p style='margin:0 0 8px;'><strong>Question:</strong> {question}</p>"
            f"<p style='margin:0;'><strong>{direction_label}:</strong> {pm_direction} | "
            f"<strong>{probability_label}:</strong> {yes_prob}%</p>"
            f"<p style='margin:6px 0 0;color:#475569;'>{match_msg}</p>"
            f"{review_html}"
        )

    return f"""
        <div style="margin-top:18px;padding:14px;border-radius:10px;
                    background:#f8fafc;border:1px solid #cbd5e1;
                    font-size:13px;line-height:1.55;color:#334155;">
            <h4 style="margin:0 0 8px;color:#0f172a;font-size:15px;">{title}</h4>
            {body}
        </div>
    """


def _build_usage_section(summary: dict) -> str:
    today_cost = summary.get("today_cost_usd", 0)
    monthly_cost = summary.get("monthly_cost_usd", 0)
    total_in = summary.get("total_input_tokens", 0)
    total_out = summary.get("total_output_tokens", 0)
    total_ws = summary.get("total_web_searches", 0)
    model = summary.get("model", CLAUDE_MODEL)
    calls = summary.get("per_call", summary.get("per_ticker", []))
    total_calls = summary.get("total_calls", len(calls))

    if REPORT_LANGUAGE == "ko":
        per_ticker_rows = ""
        for t in calls:
            call_type = t.get("call_type", "analysis")
            per_ticker_rows += (
                f"<tr><td style='padding:4px 8px;'>{t['ticker']}</td>"
                f"<td style='padding:4px 8px;'>{call_type}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['input_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['output_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['web_searches']}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>${t['cost_usd']:.4f}</td></tr>"
            )

        return f"""
        <div style="background:#f0f9ff;border-radius:12px;padding:20px;margin-bottom:24px;
                    border:1px solid #bae6fd;">
            <h3 style="margin:0 0 12px;color:#0369a1;font-size:16px;">💰 API 사용량</h3>
            <table style="width:100%;font-size:13px;border-collapse:collapse;color:#374151;">
                <tr style="background:#e0f2fe;">
                    <th style="padding:6px 8px;text-align:left;">종목</th>
                    <th style="padding:6px 8px;text-align:left;">호출</th>
                    <th style="padding:6px 8px;text-align:right;">Input</th>
                    <th style="padding:6px 8px;text-align:right;">Output</th>
                    <th style="padding:6px 8px;text-align:right;">검색</th>
                    <th style="padding:6px 8px;text-align:right;">비용</th>
                </tr>
                {per_ticker_rows}
                <tr style="border-top:2px solid #0369a1;font-weight:bold;">
                    <td style="padding:6px 8px;">합계</td>
                    <td style="padding:6px 8px;">{total_calls} calls</td>
                    <td style="padding:6px 8px;text-align:right;">{total_in:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_out:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_ws}</td>
                    <td style="padding:6px 8px;text-align:right;">${today_cost:.4f}</td>
                </tr>
            </table>
            <p style="margin:12px 0 0;font-size:13px;color:#0369a1;">
                📊 오늘 비용: <strong>${today_cost:.2f}</strong> |
                이번 달 누적: <strong>${monthly_cost:.2f}</strong> |
                모델: {model}
            </p>
        </div>"""
    else:
        per_ticker_rows = ""
        for t in calls:
            call_type = t.get("call_type", "analysis")
            per_ticker_rows += (
                f"<tr><td style='padding:4px 8px;'>{t['ticker']}</td>"
                f"<td style='padding:4px 8px;'>{call_type}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['input_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['output_tokens']:,}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>{t['web_searches']}</td>"
                f"<td style='padding:4px 8px;text-align:right;'>${t['cost_usd']:.4f}</td></tr>"
            )

        return f"""
        <div style="background:#f0f9ff;border-radius:12px;padding:20px;margin-bottom:24px;
                    border:1px solid #bae6fd;">
            <h3 style="margin:0 0 12px;color:#0369a1;font-size:16px;">💰 API Usage</h3>
            <table style="width:100%;font-size:13px;border-collapse:collapse;color:#374151;">
                <tr style="background:#e0f2fe;">
                    <th style="padding:6px 8px;text-align:left;">Ticker</th>
                    <th style="padding:6px 8px;text-align:left;">Call</th>
                    <th style="padding:6px 8px;text-align:right;">Input</th>
                    <th style="padding:6px 8px;text-align:right;">Output</th>
                    <th style="padding:6px 8px;text-align:right;">Searches</th>
                    <th style="padding:6px 8px;text-align:right;">Cost</th>
                </tr>
                {per_ticker_rows}
                <tr style="border-top:2px solid #0369a1;font-weight:bold;">
                    <td style="padding:6px 8px;">Total</td>
                    <td style="padding:6px 8px;">{total_calls} calls</td>
                    <td style="padding:6px 8px;text-align:right;">{total_in:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_out:,}</td>
                    <td style="padding:6px 8px;text-align:right;">{total_ws}</td>
                    <td style="padding:6px 8px;text-align:right;">${today_cost:.4f}</td>
                </tr>
            </table>
            <p style="margin:12px 0 0;font-size:13px;color:#0369a1;">
                📊 Today: <strong>${today_cost:.2f}</strong> |
                This Month: <strong>${monthly_cost:.2f}</strong> |
                Model: {model}
            </p>
        </div>"""


def _markdown_to_html(text: str) -> str:
    html = text
    html = re.sub(
        r"^## (.+)$",
        r"<h3 style='color:#1e40af;margin-top:20px;margin-bottom:8px;"
        r"border-bottom:2px solid #e5e7eb;padding-bottom:6px;'>\1</h3>",
        html, flags=re.MULTILINE,
    )
    html = re.sub(
        r"^### (.+)$",
        r"<h4 style='color:#1e40af;margin-top:16px;margin-bottom:6px;'>\1</h4>",
        html, flags=re.MULTILINE,
    )
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = _convert_md_tables(html)
    html = html.replace("\n", "<br>")
    return html


def _convert_md_tables(text: str) -> str:
    lines = text.split("\n")
    result = []
    table_lines = []
    in_table = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            if re.match(r"^\|[\s\-:|]+\|$", stripped):
                continue
            table_lines.append(stripped)
            in_table = True
        else:
            if in_table and table_lines:
                result.append(_table_lines_to_html(table_lines))
                table_lines = []
                in_table = False
            result.append(line)

    if table_lines:
        result.append(_table_lines_to_html(table_lines))

    return "\n".join(result)


def _table_lines_to_html(lines: list[str]) -> str:
    html = (
        "<table style='width:100%;border-collapse:collapse;margin:12px 0;"
        "font-size:13px;'>"
    )
    for i, line in enumerate(lines):
        cells = [c.strip() for c in line.strip("|").split("|")]
        tag = "th" if i == 0 else "td"
        bg = "background:#f3f4f6;" if i == 0 else ""
        border = "border:1px solid #e5e7eb;padding:6px 10px;"
        row = "<tr>"
        for cell in cells:
            row += f"<{tag} style='{border}{bg}'>{cell}</{tag}>"
        row += "</tr>"
        html += row
    html += "</table>"
    return html
